"""empty message

Revision ID: 522298c54632
Revises: 
Create Date: 2023-08-23 01:30:50.631172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522298c54632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('poems',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=4), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('poem_id', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('poem_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poem_id', 'user_id')
    )
    op.create_table('poem_category',
    sa.Column('poem_id', sa.String(length=60), nullable=False),
    sa.Column('category_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poem_id', 'category_id')
    )
    op.create_table('poem_theme',
    sa.Column('poem_id', sa.String(length=60), nullable=False),
    sa.Column('theme_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poem_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem_theme')
    op.drop_table('poem_category')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('poems')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('categories')
    # ### end Alembic commands ###
